name: Run tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'apple/**'
      - 'android/**'

jobs:
  build-docker-images:
    name: Build docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          fetch-depth: 0
      - name: 'Login to GitHub container registry'
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 # v1.14.1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the backend docker image
        run: |
          docker build . --file packages/api/Dockerfile --tag "ghcr.io/omnivore-app/backend:${GITHUB_SHA}" --tag ghcr.io/omnivore-app/backend:latest
          docker push ghcr.io/omnivore-app/backend:${GITHUB_SHA}
      - name: Build the content-fetch docker image
        run: |
          docker build --file packages/content-fetch/Dockerfile . --tag "ghcr.io/omnivore-app/content-fetch:${GITHUB_SHA}" --tag ghcr.io/omnivore-app/content-fetch:latest
          docker push ghcr.io/omnivore-app/content-fetch:${GITHUB_SHA}
