---
name: Semgrep Full Scan
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 1 * * 6'
permissions:  # added using https://github.com/step-security/secure-repo
  contents: read
jobs:
  semgrep-full:
      permissions:
        contents: read # for actions/checkout to fetch code
        security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      runs-on: ubuntu-latest
      container:
        image: returntocorp/semgrep

      steps:
        # step 1
        - name: clone application source code
          uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

        # step 2
        - name: full scan
          run: |
            semgrep \
              --sarif --output report.sarif \
              --metrics=off \
              --config="p/default"

        # step 3
        - name: save report as pipeline artifact
          uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
          with:
            name: report.sarif
            path: report.sarif

        # step 4
        - name: publish code scanning alerts
          uses: github/codeql-action/upload-sarif@ceaec5c11a131e0d282ff3b6f095917d234caace # v2.25.3
          with:
            sarif_file: report.sarif
            category: semgrep
